/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: parser/gohash/gohash.i

package gohash

/*
#define intgo swig_intgo
typedef void *swig_voidp;
#cgo LDFLAGS: -L/home/virtualsoundnw/lightwalletd -l:veruslib.so -L/usr/lib/x86_64-linux-gnu -l:libboost_system.so

#include <stdint.h>


typedef long long intgo;
typedef unsigned long long uintgo;



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;


typedef _gostring_ swig_type_1;
typedef _gostring_ swig_type_2;
typedef _gostring_ swig_type_3;
typedef _gostring_ swig_type_4;
typedef _gostring_ swig_type_5;
typedef _gostring_ swig_type_6;
typedef _gostring_ swig_type_7;
typedef _gostring_ swig_type_8;
typedef _gostring_ swig_type_9;
typedef _gostring_ swig_type_10;
typedef _gostring_ swig_type_11;
typedef _gostring_ swig_type_12;
typedef _gostring_ swig_type_13;
typedef _gostring_ swig_type_14;
typedef _gostring_ swig_type_15;
typedef _gostring_ swig_type_16;
typedef _gostring_ swig_type_17;
typedef _gostring_ swig_type_18;
typedef _gostring_ swig_type_19;
typedef _gostring_ swig_type_20;
typedef _gostring_ swig_type_21;
typedef _gostring_ swig_type_22;
extern void _wrap_Swig_free_gohash_65cfb16cc4341895(uintptr_t arg1);
extern uintptr_t _wrap_Swig_malloc_gohash_65cfb16cc4341895(swig_intgo arg1);
extern void _wrap_Gohash_result_set_gohash_65cfb16cc4341895(uintptr_t arg1, swig_voidp arg2);
extern swig_voidp _wrap_Gohash_result_get_gohash_65cfb16cc4341895(uintptr_t arg1);
extern swig_type_1 _wrap_Gohash_verushash_gohash_65cfb16cc4341895(uintptr_t arg1, swig_type_2 arg2, swig_intgo arg3);
extern swig_type_3 _wrap_Gohash_verushash_reverse_gohash_65cfb16cc4341895(uintptr_t arg1, swig_type_4 arg2, swig_intgo arg3);
extern swig_type_5 _wrap_Gohash_verushash_v2_gohash_65cfb16cc4341895(uintptr_t arg1, swig_type_6 arg2, swig_intgo arg3);
extern swig_type_7 _wrap_Gohash_verushash_v2_reverse_gohash_65cfb16cc4341895(uintptr_t arg1, swig_type_8 arg2, swig_intgo arg3);
extern swig_type_9 _wrap_Gohash_vh_v2_gohash_65cfb16cc4341895(uintptr_t arg1, swig_type_10 arg2, swig_intgo arg3);
extern swig_type_11 _wrap_Gohash_verushash_v2b_gohash_65cfb16cc4341895(uintptr_t arg1, swig_type_12 arg2, swig_intgo arg3);
extern swig_type_13 _wrap_Gohash_verushash_v2b_reverse_gohash_65cfb16cc4341895(uintptr_t arg1, swig_type_14 arg2, swig_intgo arg3);
extern swig_type_15 _wrap_Gohash_vh_v2b_gohash_65cfb16cc4341895(uintptr_t arg1, swig_type_16 arg2, swig_intgo arg3);
extern swig_type_17 _wrap_Gohash_verushash_v2b1_gohash_65cfb16cc4341895(uintptr_t arg1, swig_type_18 arg2, swig_intgo arg3);
extern swig_type_19 _wrap_Gohash_verushash_v2b1_reverse_gohash_65cfb16cc4341895(uintptr_t arg1, swig_type_20 arg2, swig_intgo arg3);
extern swig_type_21 _wrap_Gohash_vh_v2b1_gohash_65cfb16cc4341895(uintptr_t arg1, swig_type_22 arg2, swig_intgo arg3);
extern uintptr_t _wrap_new_Gohash_gohash_65cfb16cc4341895(void);
extern void _wrap_delete_Gohash_gohash_65cfb16cc4341895(uintptr_t arg1);
#undef intgo
*/
import "C"

import "unsafe"
import _ "runtime/cgo"
import "sync"


type _ unsafe.Pointer



var Swig_escape_always_false bool
var Swig_escape_val interface{}


type _swig_fnptr *byte
type _swig_memberptr *byte


type _ sync.Mutex


type swig_gostring struct { p uintptr; n int }
func swigCopyString(s string) string {
  p := *(*swig_gostring)(unsafe.Pointer(&s))
  r := string((*[0x7fffffff]byte)(unsafe.Pointer(p.p))[:p.n])
  Swig_free(p.p)
  return r
}

func Swig_free(arg1 uintptr) {
	_swig_i_0 := arg1
	C._wrap_Swig_free_gohash_65cfb16cc4341895(C.uintptr_t(_swig_i_0))
}

func Swig_malloc(arg1 int) (_swig_ret uintptr) {
	var swig_r uintptr
	_swig_i_0 := arg1
	swig_r = (uintptr)(C._wrap_Swig_malloc_gohash_65cfb16cc4341895(C.swig_intgo(_swig_i_0)))
	return swig_r
}

type SwigcptrGohash uintptr

func (p SwigcptrGohash) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrGohash) SwigIsGohash() {
}

func (arg1 SwigcptrGohash) SetResult(arg2 *byte) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Gohash_result_set_gohash_65cfb16cc4341895(C.uintptr_t(_swig_i_0), C.swig_voidp(_swig_i_1))
}

func (arg1 SwigcptrGohash) GetResult() (_swig_ret *byte) {
	var swig_r *byte
	_swig_i_0 := arg1
	swig_r = (*byte)(C._wrap_Gohash_result_get_gohash_65cfb16cc4341895(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrGohash) Verushash(arg2 string, arg3 int) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r_p := C._wrap_Gohash_verushash_gohash_65cfb16cc4341895(C.uintptr_t(_swig_i_0), *(*C.swig_type_2)(unsafe.Pointer(&_swig_i_1)), C.swig_intgo(_swig_i_2))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func (arg1 SwigcptrGohash) Verushash_reverse(arg2 string, arg3 int) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r_p := C._wrap_Gohash_verushash_reverse_gohash_65cfb16cc4341895(C.uintptr_t(_swig_i_0), *(*C.swig_type_4)(unsafe.Pointer(&_swig_i_1)), C.swig_intgo(_swig_i_2))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func (arg1 SwigcptrGohash) Verushash_v2(arg2 string, arg3 int) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r_p := C._wrap_Gohash_verushash_v2_gohash_65cfb16cc4341895(C.uintptr_t(_swig_i_0), *(*C.swig_type_6)(unsafe.Pointer(&_swig_i_1)), C.swig_intgo(_swig_i_2))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func (arg1 SwigcptrGohash) Verushash_v2_reverse(arg2 string, arg3 int) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r_p := C._wrap_Gohash_verushash_v2_reverse_gohash_65cfb16cc4341895(C.uintptr_t(_swig_i_0), *(*C.swig_type_8)(unsafe.Pointer(&_swig_i_1)), C.swig_intgo(_swig_i_2))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func (arg1 SwigcptrGohash) Vh_v2(arg2 string, arg3 int) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r_p := C._wrap_Gohash_vh_v2_gohash_65cfb16cc4341895(C.uintptr_t(_swig_i_0), *(*C.swig_type_10)(unsafe.Pointer(&_swig_i_1)), C.swig_intgo(_swig_i_2))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func (arg1 SwigcptrGohash) Verushash_v2b(arg2 string, arg3 int) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r_p := C._wrap_Gohash_verushash_v2b_gohash_65cfb16cc4341895(C.uintptr_t(_swig_i_0), *(*C.swig_type_12)(unsafe.Pointer(&_swig_i_1)), C.swig_intgo(_swig_i_2))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func (arg1 SwigcptrGohash) Verushash_v2b_reverse(arg2 string, arg3 int) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r_p := C._wrap_Gohash_verushash_v2b_reverse_gohash_65cfb16cc4341895(C.uintptr_t(_swig_i_0), *(*C.swig_type_14)(unsafe.Pointer(&_swig_i_1)), C.swig_intgo(_swig_i_2))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func (arg1 SwigcptrGohash) Vh_v2b(arg2 string, arg3 int) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r_p := C._wrap_Gohash_vh_v2b_gohash_65cfb16cc4341895(C.uintptr_t(_swig_i_0), *(*C.swig_type_16)(unsafe.Pointer(&_swig_i_1)), C.swig_intgo(_swig_i_2))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func (arg1 SwigcptrGohash) Verushash_v2b1(arg2 string, arg3 int) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r_p := C._wrap_Gohash_verushash_v2b1_gohash_65cfb16cc4341895(C.uintptr_t(_swig_i_0), *(*C.swig_type_18)(unsafe.Pointer(&_swig_i_1)), C.swig_intgo(_swig_i_2))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func (arg1 SwigcptrGohash) Verushash_v2b1_reverse(arg2 string, arg3 int) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r_p := C._wrap_Gohash_verushash_v2b1_reverse_gohash_65cfb16cc4341895(C.uintptr_t(_swig_i_0), *(*C.swig_type_20)(unsafe.Pointer(&_swig_i_1)), C.swig_intgo(_swig_i_2))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func (arg1 SwigcptrGohash) Vh_v2b1(arg2 string, arg3 int) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r_p := C._wrap_Gohash_vh_v2b1_gohash_65cfb16cc4341895(C.uintptr_t(_swig_i_0), *(*C.swig_type_22)(unsafe.Pointer(&_swig_i_1)), C.swig_intgo(_swig_i_2))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func NewGohash() (_swig_ret Gohash) {
	var swig_r Gohash
	swig_r = (Gohash)(SwigcptrGohash(C._wrap_new_Gohash_gohash_65cfb16cc4341895()))
	return swig_r
}

func DeleteGohash(arg1 Gohash) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_Gohash_gohash_65cfb16cc4341895(C.uintptr_t(_swig_i_0))
}

type Gohash interface {
	Swigcptr() uintptr
	SwigIsGohash()
	SetResult(arg2 *byte)
	GetResult() (_swig_ret *byte)
	Verushash(arg2 string, arg3 int) (_swig_ret string)
	Verushash_reverse(arg2 string, arg3 int) (_swig_ret string)
	Verushash_v2(arg2 string, arg3 int) (_swig_ret string)
	Verushash_v2_reverse(arg2 string, arg3 int) (_swig_ret string)
	Vh_v2(arg2 string, arg3 int) (_swig_ret string)
	Verushash_v2b(arg2 string, arg3 int) (_swig_ret string)
	Verushash_v2b_reverse(arg2 string, arg3 int) (_swig_ret string)
	Vh_v2b(arg2 string, arg3 int) (_swig_ret string)
	Verushash_v2b1(arg2 string, arg3 int) (_swig_ret string)
	Verushash_v2b1_reverse(arg2 string, arg3 int) (_swig_ret string)
	Vh_v2b1(arg2 string, arg3 int) (_swig_ret string)
}


